version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/database:/app/database
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/3
      - MAILHOG_HOST=mailhog
      - FRONTEND_URL=http://frontend:5173
    depends_on:
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - app_network

  celery_worker:
    build: ./backend
    command: celery -A app.celery worker --pool=solo --loglevel=info
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/3
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - app_network

  celery_beat:
    build: ./backend
    command: celery -A app.celery beat --loglevel=info
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/3
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_BACKEND_URL=http://localhost:5000
    networks:
      - app_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-server", "--test-memory", "1"]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - app_network

networks:
  app_network:
    driver: bridge